export const contacts = [
  {
    id: '1',
    name: 'Mike Huston',
    email: 'mikehuston@live.com',
    phone: '0692384587',
    about: 'Product Manager at Alibaba Traders.co',
    company: 'Alibaba Traders.co',
    address: '47, west shewraoara pirerbag road mirpur,dhaka',
  },
  {
    id: '2',
    name: 'Amazonia',
    email: 'Amazonia@live.com',
    phone: '0692384587',
    about: 'Product Manager at Amazonia',
    company: 'Amazonia online',
    address: '47, west shewraoara pirerbag road mirpur,dhaka',
  },
  {
    id: '3',
    name: 'Mike Huston',
    email: 'mikehuston@live.com',
    phone: '0692384587',
    about: 'Product Manager at Alibaba Traders.co',
    company: 'Alibaba Traders.co',
    address: '47, west shewraoara pirerbag road mirpur,dhaka',
  },
  {
    id: '4',
    name: 'Amazonia',
    email: 'Amazonia@live.com',
    phone: '0692384587',
    about: 'Product Manager at Amazonia',
    company: 'Amazonia online',
    address: '47, west shewraoara pirerbag road mirpur,dhaka',
  },
  {
    id: '5',
    name: 'Mike Huston',
    email: 'mikehuston@live.com',
    phone: '0692384587',
    about: 'Product Manager at Alibaba Traders.co',
    company: 'Alibaba Traders.co',
    address: '47, west shewraoara pirerbag road mirpur,dhaka',
  },
];
